/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Data_pins_aliases.h"
#include "Data_pins.h"
#include "Master.h"
#include "Master_PVT.h"
#include "LED_RED_aliases.h"
#include "LED_RED.h"
#include "LED_GREEN_aliases.h"
#include "LED_GREEN.h"
#include "LED_BLUE_aliases.h"
#include "LED_BLUE.h"
#include "timer_clock.h"
#include "Sampling_timer.h"
#include "Poll_intr.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

